url: "https://wiredjohn.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "wiredjohn.com" # the name of your site, e.g. ACME Corp.

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

include:
  - e1b6d7bf5c9344078700e29cff72914a.txt

permalink: /:categories/:year/:month/:day/:title

collections:
  - recap_items    