url: "https://wiredjohn.com"
baseurl: "" # the subpath of your site, e.g. /blog
title: "wiredjohn.com"
description: "Web development and design blog by John, featuring real projects, experiments, and mindless rambling."
author:
  name: WiredJohn

twitter:
  card: summary_large_image

# logo: /assets/img/common/logo.gif

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from

include:
  - e1b6d7bf5c9344078700e29cff72914a.txt

permalink: /:categories/:year/:month/:day/:title

collections:
  - recap_items    